### ISSUE TITLE
Question: Not getting error. What am I doing wrong.

### ISSUE THREAD

**Issue by davout1806** [final-hill/decorator-contracts#180]
Apologies if I'm doing something stupid.

Initially tried to use this lib as normal `npm i @final-hill/decorator-contracts`in my own project but could not get it to work. So I thought maybe it was my project - as it is my first typescript project. So then I performed the following:
1. downloaded all the code as a zip
2. unzipped
3. cd into decorator-contracts-master
4. ran `npm i`
5. ran `npm run test` - everything passed
6. created the 2 files below in the decorator-contracts-master/src directory 
7. ran `./node_modules/.bin/tsc` no errors
8. ran `node dist/stackCheck.js` got undefined rather than an AssertionError as I expected.

**Stack.ts** (your code from readme)
```
import Contracts from './';
let {invariant} = new Contracts(true);

@invariant<Stack<any>>(self => self.size >= 0 && self.size <= self.limit)
@invariant<Stack<any>>(self => self.isEmpty() == (self.size == 0))
@invariant<Stack<any>>(self => self.isFull() == (self.size == self.limit))
class Stack<T> {
  #implementation: T[] = [];

  constructor(readonly limit: number) {}

  clear(): void {
    this.#implementation = [];
  }

  isEmpty(): boolean {
    return this.#implementation.length == 0;
  }

  isFull(): boolean {
    return this.#implementation.length == this.limit;
  }

  pop(): T {
    return this.#implementation.pop()!;
  }

  push(item: T): void {
    this.#implementation.push(item);
  }

  get size(): number {
    return this.#implementation.length;
  }

  top(): T {
    return this.#implementation[this.#implementation.length - 1];
  }
}

export default Stack
```

**stackCheck.ts**
```
import Stack from "./Stack.js"
let myStack = new Stack(3)

console.log(myStack.pop())
```

Any help would be appreciated. Thanks

**Comment by mlhaufe** [comment]
Two things.

First, there is a bug in the example code. When you pop an empty array the length is still `0`; so `self.size >= 0` will always be true. 

A better example would be to track the size separately from the implementation:

```typescript
class Stack<T> {
    #size = 0;
    #implementation: T[] = [];

    constructor(readonly limit: number) {}

    clear(): void {
        this.#implementation = [];
    }

    isEmpty(): boolean {
        return this.#size == 0;
    }

    isFull(): boolean {
        return this.#size == this.limit;
    }

    pop(): T {
        this.#size--;

        return this.#implementation.pop()!;
    }

    push(item: T): void {
        this.#size++;
        this.#implementation.push(item);
    }

    get size(): number {
        return this.#size;
    }

    top(): T {
        return this.#implementation[this.#implementation.length - 1];
    }
}
```

Second, I think there is a subtle bug with multiple `@invariant` declarations on the class. Behind the scenes this turns the class into a proxy and with multiple `@invariants` it can have trouble identifying the original class. The workaround here is to use a single declaration:

```typescript
@invariant<Stack<any>>(self =>
    self.size >= 0 && self.size <= self.limit &&
    self.isEmpty() == (self.size == 0) &&
    self.isFull() == (self.size == self.limit)
)
```

FYI, I have a new version of the library that will be released soon that fixes these issues and improves usability. An example of what the new approach will (mostly) look like can be seen [here](https://github.com/final-hill/decorator-contracts/issues/158#issuecomment-743301359). I estimate a week before it is released.

**Comment by mlhaufe** [comment]
The new version (v0.20.0) has been published.
